[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#7765E7"
backgroundColor = "#F8F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#24212F"
font = "sans serif"

[server]
headless = true
maxUploadSize = 20
