[theme]
primaryColor = "#1F5F99"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EEF5FB"
textColor = "#26384A"
font = "sans serif"

[server]
headless = true
maxUploadSize = 20

[client]
showErrorDetails = "none"
toolbarMode = "minimal"
